# Multiple Linear Regression (Simple Example)

Predict a target from **several** features using the closed-form **Normal Equation**:

$$\hat{\boldsymbol{\beta}} = (\mathbf{X}^{\top}\mathbf{X})^{-1}\,\mathbf{X}^{\top}\mathbf{y}$$

so that $\hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots$


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Dataset: 5 houses. Features: [Size_SqFt, Bedrooms, Age_Years]
X = np.array([
    [1200, 2, 10],
    [1800, 3, 5],
    [2400, 4, 2],
    [1500, 3, 20],
    [3000, 4, 1],
], dtype=float)

y = np.array([210000, 290000, 380000, 230000, 450000], dtype=float)

feature_names = ["Size_SqFt", "Bedrooms", "Age_Years"]
df = pd.DataFrame(X, columns=feature_names)
df["Price_USD"] = y
print(df)


   Size_SqFt  Bedrooms  Age_Years  Price_USD
0     1200.0       2.0       10.0   210000.0
1     1800.0       3.0        5.0   290000.0
2     2400.0       4.0        2.0   380000.0
3     1500.0       3.0       20.0   230000.0
4     3000.0       4.0        1.0   450000.0


## Fit with the Normal Equation

We prepend a column of 1s to `X` for the intercept, then apply
$\boldsymbol{\beta} = (\mathbf{X}^{\top}\mathbf{X})^{-1}\mathbf{X}^{\top}\mathbf{y}$.


In [3]:
X_design = np.hstack([np.ones((X.shape[0], 1)), X])  # add intercept column
print("=== DESIGN MATRIX ===")
print(pd.DataFrame(X_design, columns=["Intercept"] + feature_names)
beta = np.linalg.inv(X_design.T @ X_design) @ X_design.T @ y

intercept = beta[0]
coef = beta[1:]

print("=== LEARNED PARAMETERS ===")
print(f"Intercept (beta_0)            : {intercept:,.2f}")
for name, c in zip(feature_names, coef):
    print(f"{name:<12} coefficient        : {c:,.2f}")


=== DESIGN MATRIX ===
[[1.0e+00 1.2e+03 2.0e+00 1.0e+01]
 [1.0e+00 1.8e+03 3.0e+00 5.0e+00]
 [1.0e+00 2.4e+03 4.0e+00 2.0e+00]
 [1.0e+00 1.5e+03 3.0e+00 2.0e+01]
 [1.0e+00 3.0e+03 4.0e+00 1.0e+00]]
=== LEARNED PARAMETERS ===
Intercept (beta_0)            : 72,235.12
Size_SqFt    coefficient        : 118.00
Bedrooms     coefficient        : 6,458.42
Age_Years    coefficient        : -1,914.31


## Performance Metrics & Residual Analysis


In [ ]:
y_pred = X_design @ beta
residuals = y - y_pred

mse = np.mean(residuals ** 2)
rmse = np.sqrt(mse)
ss_res = np.sum(residuals ** 2)
ss_tot = np.sum((y - np.mean(y)) ** 2)
r2 = 1 - ss_res / ss_tot

print("=== METRICS ===")
print(f"Mean Squared Error (MSE) : {mse:,.2f}")
print(f"Root MSE (RMSE)          : {rmse:,.2f}")
print(f"R-squared (R2)           : {r2:.4f}")

res_df = pd.DataFrame({
    "Actual": np.round(y, 1),
    "Predicted": np.round(y_pred, 1),
    "Residual": np.round(residuals, 1),
})
print()
print("=== PER-POINT RESIDUALS ===")
print(res_df.to_string(index=False))


## Plots


In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Actual vs Predicted
axes[0].scatter(y, y_pred, color="indigo", edgecolor="black", s=80, zorder=5)
axes[0].plot([y.min(), y.max()], [y.min(), y.max()], color="darkorange", linestyle="--", lw=2, label="Perfect fit")
axes[0].set_title("Actual vs Predicted")
axes[0].set_xlabel("Actual Price ($)")
axes[0].set_ylabel("Predicted Price ($)")
axes[0].legend()
axes[0].grid(True, linestyle="--", alpha=0.4)

# Residuals vs Predicted
axes[1].axhline(0, color="red", linestyle="--", lw=1.5)
axes[1].scatter(y_pred, residuals, color="purple", edgecolor="black", s=80, zorder=5)
axes[1].set_title("Residuals vs Predicted")
axes[1].set_xlabel("Predicted Price ($)")
axes[1].set_ylabel("Residual ($)")
axes[1].grid(True, linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()


## Coefficient Interpretation


In [ ]:
coef_df = pd.DataFrame({
    "Feature": ["Intercept"] + feature_names,
    "Beta": np.round(beta, 4),
})
print(coef_df.to_string(index=False))
